/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ru.nsu.shatalov.g19214;

import org.junit.Test;

import java.util.Arrays;
import java.util.concurrent.ExecutionException;

public class FinderTest {
    @Test
    public void test() throws ExecutionException, InterruptedException {
        Finder threadFind = new Finder();
        long end, start;
        Integer[] arr = new Integer[8000];
        Arrays.fill(arr, 1000000007);
        for (int j = 1; j <= 3; j++) {
            System.out.println("Run " + j + ":");
            for (int i = 1; i <= Runtime.getRuntime().availableProcessors(); i++) {
                start = System.currentTimeMillis();
                threadFind.find(arr, i);
                end = System.currentTimeMillis();
                System.out.println("Time for " + i + " thread(s): " + ((double) end - start) / 10000);
            }
        }
    }
}

