/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ru.nsu.fit.g18214.shatalov;

import org.junit.Assert;
import org.junit.Test;
import static org.junit.Assert.*;

public class HeapSortTests {
    @Test
    public void test(){
        HeapSort gen = new HeapSort();
        Assert.assertArrayEquals(
                new int[] {1, 2, 3, 4, 5},
                gen.getAnswer(new int[] {5, 4, 3, 2, 1}));
        Assert.assertArrayEquals(
                new int[] {-100, -1, 1, 2, 2, 3, 4},
                gen.getAnswer(new int[] {1, 2, -100, -1, 3, 4, 2,}));
        Assert.assertArrayEquals(
                new int[] {-1, -1, -1, -1},
                gen.getAnswer(new int[] {-1, -1, -1, -1}));
        Assert.assertArrayEquals(
                new int[] {1},
                gen.getAnswer(new int[] {1}));
    }
}
