/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ru.nsu.fit.g18214.shatalov;

import org.junit.Assert;
import org.junit.Test;
import static org.junit.Assert.*;

public class HeapSortTests {
    @Test
    public void test(){
        HeapSort gen = new HeapSort();

        int[] arr = {5,3,4,2,1};
        gen.sort(arr);
        Assert.assertArrayEquals(
                new int[] {1, 2, 3, 4, 5},
                arr);
        arr = new int[] {-1, 1, 2, 3, 4, 2, -100};
        gen.sort(arr);
        Assert.assertArrayEquals(
                new int[] {-100, -1, 1, 2, 2, 3, 4},
                arr);
        arr = new int[] {-1, -1, -1, -1};
        gen.sort(arr);
        Assert.assertArrayEquals(
                new int[] {-1, -1, -1, -1},
                arr);
        arr = new int[] {1};
        gen.sort(arr);
        Assert.assertArrayEquals(
                new int[] {1},
                arr);
        arr = new int[] {};
        gen.sort(arr);
        Assert.assertArrayEquals(
                new int [] {},
                arr);
        arr = null;
        gen.sort(arr);
        Assert.assertArrayEquals(
                null,
                arr);
        arr = new int[] {3, 2, 1, 4};
        gen.sort(arr);
        Assert.assertArrayEquals(
                new int [] {1,2,3,4},
                arr);
        arr = new int[] {-1, 1, -1};
        gen.sort(arr);
        Assert.assertArrayEquals(
                new int [] {-1,-1,1},
                arr);
    }
}
