/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ru.nsu.fit.g18214.shatalov;

import java.io.*;
import java.util.ArrayList;
import java.util.List;

public class FindSubstring {
    public static String[] read(String filename) throws IOException {
        FileReader fileReader = new FileReader(filename);
        BufferedReader bufferedReader = new BufferedReader(fileReader);

        List<String> lines = new ArrayList<String>();
        String line = null;

        while ((line = bufferedReader.readLine()) != null) {
            lines.add(line);
        }

        bufferedReader.close();
        return lines.toArray(new String[lines.size()]);
    }

    public static Integer[] indexIn(String substring) throws IOException {

        FindSubstring fs = new FindSubstring();
        String[] lines = fs.read("src/main/resources/input.txt");

        ArrayList<Integer> index = new ArrayList<>();

        for (String line : lines)

            for (int i = 0; i < line.length(); i++) {
                int tmp;
                tmp = line.indexOf(substring, i);
                if (tmp != -1) {
                    index.add(tmp);
                    i = tmp + substring.length();
                }
                else
                    break;
            }

        return index.toArray(new Integer[index.size()]);
    }

    public static void main(String[] args) throws IOException {
        FindSubstring fs = new FindSubstring();

        Integer[] arr;
        arr = fs.indexIn("me");

        System.out.print("{");
        for (int i = 0; i < arr.length; i++) {
            System.out.print(arr[i]);
            if (i < arr.length - 1)
                System.out.print(", ");
        }
        System.out.print("}");
    }
}
