/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ru.nsu.fit.g18214.shatalov;

import org.junit.Test;
import static org.junit.Assert.*;

public class FindSubstringTest {

}
