/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ru.nsu.fit.g18214.shatalov;

import org.junit.Assert;
import org.junit.Test;

import java.io.IOException;

public class FindSubstringTest {

  @Test
  public void testSingle() throws IOException {
    FindSubstring gen = new FindSubstring();
    Assert.assertArrayEquals(
        new Integer[]{7},
        gen.readAndFind("пирог",
            "src/main/resources/input.txt"));

    Assert.assertArrayEquals(
        new Integer[]{3},
        gen.readAndFind("родился",
            "src/main/resources/testFile_2.txt")
    );

    Assert.assertArrayEquals(
        new Integer[]{0},
        gen.readAndFind("Ты",
            "src/main/resources/testFile_2.txt")
    );

    Assert.assertArrayEquals(
        new Integer[]{5828},
        gen.readAndFind("Nathalie",
            "src/main/resources/testFile_3.txt")
    );

    Assert.assertArrayEquals(
        new Integer[] {3043},
        gen.readAndFind("madame de Genlis",
            "src/main/resources/testFile_3.txt")
    );
  }

  @Test
  public void testMultiple() throws IOException {
    FindSubstring gen = new FindSubstring();
    Assert.assertArrayEquals(
        new Integer[]{2416, 2643, 4259, 5428, 5675, 5857, 6339, 7231},
        gen.readAndFind("Я",
            "src/main/resources/testFile_3.txt")
    );
  }

  @Test
  public void testEmpty() throws IOException {
    FindSubstring gen = new FindSubstring();
    Assert.assertArrayEquals(
        new Integer[] {},
        gen.readAndFind("дурак",
            "src/main/resources/testFile_3.txt")
    );

    Assert.assertArrayEquals(
        new Integer[]{},
        gen.readAndFind("пирог",
            "src/main/resources/testFile_1.txt")
    );
  }

}
